name: Android Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'art/**'
      - 'README*'
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    outputs:
      should_release: ${{ steps.whether_release.outputs.should_release }}
      
    steps:
    - uses: actions/checkout@v5
    - name: set up JDK 20
      uses: actions/setup-java@v5
      with:
        java-version: '20'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: AdoptiveParentBelarus
          path: ${{ env.output_files }}

    - name: Determine whether release
      id: whether_release
      run: |
          if [[ "${{ github.event.head_commit.message }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "should_release=true" >> $GITHUB_OUTPUT
          fi

  release:
      name: Release
      needs: build
      if: needs.build.outputs.should_release
      runs-on: ubuntu-22.04

      permissions:
          contents: write

      steps:
      - uses: actions/download-artifact@v5

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.head_commit.message }}
          files: ${{ env.articact_filesS }}
          generate_release_notes: true
          prerelease: true

      - uses: geekyeggo/delete-artifact@v2
        with:
          name: '*'
          failOnError: false
